### ISSUE TITLE
Still bike4brussels colors on interaction with switch button

### ISSUE THREAD

**Issue by xivk** [anyways-open/genk-cycling-frontend#40]
This still has incorrect colors after/during interactions:

![image](https://user-images.githubusercontent.com/1128068/54984786-8457f380-4fa7-11e9-8d02-32384c33a7a1.png)

**Comment by xivk** [comment]
Cannot figure this out:

![Peek 2019-03-29 17-31](https://user-images.githubusercontent.com/1128068/55251514-b2a82e00-5248-11e9-826a-f09ac6f8d8bc.gif)

**Comment by jbelien** [comment]
Haha, it took me a while but I think I found it 💪

It comes from Bootstrap, see https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L2411

```css
.btn-warning:not(:disabled):not(.disabled):active, 
.btn-warning:not(:disabled):not(.disabled).active,
.show > .btn-warning.dropdown-toggle {
  color: #212529;
  background-color: #d39e00;
  border-color: #c69500;
}
```

You'll have to "overwrite" `.btn-warning:not(:disabled):not(.disabled):active` and `.btn-warning:not(:disabled):not(.disabled).active` with your "Genk color" in your own CSS.

**Comment by jbelien** [comment]
You'll also have to "overwrite" `.btn-warning:not(:disabled):not(.disabled):active:focus` and `.btn-warning:not(:disabled):not(.disabled).active:focus` for the border.

See https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L2417

```css
.btn-warning:not(:disabled):not(.disabled):active:focus, 
.btn-warning:not(:disabled):not(.disabled).active:focus,
.show > .btn-warning.dropdown-toggle:focus {
  box-shadow: 0 0 0 0.2rem rgba(222, 170, 12, 0.5);
}
```
